export const REGISTER = "register",
  AUTENTICAR_TOKEN = "AUTENTICAR_TOKEN",
  USER = "user",
  FETCH_CATEGORIAS = "FETCH_CATEGORIAS",
  FETCH_DADOS = "fetch_dados",
  FETCH_PRODUTOS = "FETCH_PRODUTOS";